### ISSUE TITLE
Send notifications?

### ISSUE THREAD

**Issue by schumi2004** [elbowz/xbmc.service.pushbullet#1]
Nice addon. 
I was wondering if your planning to let it send notifications also instead of receiving only?
Would be nice if it could send notifications based on certain actions, for example:
System updates
Addon updates
Start/finished watching
etc.

**Comment by elbowz** [comment]
whaoo...you are a speedy man, I have just published this add-on ;)

Yeah, I though something like your suggestion. If you see in my thread, you can find that:

> Q: Do you think can be useful that Kodi send notifications to others devices? (es. "now playing..." or whatever is notified in Kodi)

It's quite simple send notification (push) for my add-on, the trouble is catch they from XBMC.

can you do a list of what you want Pushbullet send?
would you like chose who is the receiver of this push? or just everyone?
- System updates: what you mean?
- Addon updates: what you mean?
- Start/finished watching: ok no problem
- XBMC notification:  ok no problem

**Comment by schumi2004** [comment]
In short to answer your questions.
By system updates i was talking about OpenELEC updates and or XBMC updates itself checked by XBMC version checker. 
Addon updates isn't that interesting since it can be updated automatic, drop that.
If you mention to trigger PB based on XBMC notifications you could do almost anything.

Start/finished watching I can explain. Previously i got notifications in PB from Trakt.tv rss feed but it's slow (only checks every 15 minutes) and based on those triggers in PB i performed certain tasks on my Android phone using Tasker app. Using your addon would allow me trigger tasks with PB faster since it would be instant. 

What i would like to have send is Series/Movie title and maybe trakt.tv url for it, (if possible).
You could let it send PB messages when series/movies is watched for a certain % (80% for example) like is done in Trakt addon.
And pushed to everyone would be a start but having it select device to send to would be even more nice.

But it seems I missed the official topic, i'll jump over there.

**Comment by elbowz** [comment]
I'm curious: What are the "certain task" that you perform on you Android using Tasker?

I think I'm able to trig Xbmc update (they are only xbmc notification like this [Notification](http://thedigitallifestyle.com/w/wp-content/uploads/2013/02/image29.png))....but finished watching? It's too strange..

I can create some internal API, for other addons that want user pushbullet.

**Comment by schumi2004** [comment]
Some tasks that could be done are: Turn off/on lights, send message to a whatsapp group or silence my phone etc
But what i do with Push Bullet messages received on my mobile has nothing to do with the addon itself ;)

**Comment by elbowz** [comment]
I like have new inspirations :)

**Comment by elbowz** [comment]
@schumi2004 I don't think xbmc add-on is able to catch xbmc Notification...

Seems that the only things that can catch are:

```
7 Notifications
7.1 Application
7.1.1 Application.OnVolumeChanged
7.2 AudioLibrary
7.2.1 AudioLibrary.OnCleanFinished
7.2.2 AudioLibrary.OnCleanStarted
7.2.3 AudioLibrary.OnRemove
7.2.4 AudioLibrary.OnScanFinished
7.2.5 AudioLibrary.OnScanStarted
7.2.6 AudioLibrary.OnUpdate
7.3 Input
7.3.1 Input.OnInputFinished
7.3.2 Input.OnInputRequested
7.4 Player
7.4.1 Player.OnPause
7.4.2 Player.OnPlay
7.4.3 Player.OnPropertyChanged
7.4.4 Player.OnSeek
7.4.5 Player.OnSpeedChanged
7.4.6 Player.OnStop
7.5 Playlist
7.5.1 Playlist.OnAdd
7.5.2 Playlist.OnClear
7.5.3 Playlist.OnRemove
7.6 System
7.6.1 System.OnLowBattery
7.6.2 System.OnQuit
7.6.3 System.OnRestart
7.6.4 System.OnSleep
7.6.5 System.OnWake
7.7 VideoLibrary
7.7.1 VideoLibrary.OnCleanFinished
7.7.2 VideoLibrary.OnCleanStarted
7.7.3 VideoLibrary.OnRemove
7.7.4 VideoLibrary.OnScanFinished
7.7.5 VideoLibrary.OnScanStarted
7.7.6 VideoLibrary.OnUpdate
```

With this event I can trigger start/finished playback...but not system updates.

I have opened a thread for understand more (http://forum.xbmc.org/showthread.php?tid=205134)
