### ISSUE TITLE
Service does not connect to push server after authentication - requires Kodi restart

### ISSUE THREAD

**Issue by ruuk** [elbowz/xbmc.service.pushbullet#12]

**Comment by elbowz** [comment]
Here is the problem: https://github.com/elbowz/xbmc.service.pushbullet/blob/develop/service.py#L140

I don't know why `__addon__.getSetting('pb_access_token')` return the old setting and not change

**Comment by ruuk** [comment]
Well, I'll look at it when I get a chance. I do want to fix this before we put it on the official repository. 

Also, when I post an issue, I don't expect you to be the one to fix it. You can if you want to and have the time of course, but I just want you to know that's not why post them :) it's just a good way remember them and let everyone know it's a known issue.

**Comment by elbowz** [comment]
Yeah, I agree with you...and as you said, I had free time.

At the end, I haven't fix it ;)

**Comment by ruuk** [comment]
Fixed by c4784aecf64da8f128d027adc5c3bce07c65ed22
