### ISSUE TITLE
the number of caller, in android stock is in the notification title

### ISSUE THREAD

**Issue by grenryd** [elbowz/xbmc.service.pushbullet#18]
I'm using this addon to mirror the phones to xbmc.
I have a Samsung note 3 and everything works great but my girlfriend have a galaxy nexus and when someone is calling her it only displays:
"Incoming Call" and not the contact name as when someone calls my phone.

The problem is that add-on view only:
- Android Application name => Kodi Notification title
- Android Notification body => Kodi notification sub-title

the number of caller, in android stock is in the notification title

http://forum.kodi.tv/showthread.php?tid=204567&pid=1834637#pid1834637

**Comment by elbowz** [comment]
thanks for issue reporting!

It's fixed in ea5c21619400e7478cf0dd51651b262203c36c45

Wait for 0.8.14b release :)

**Comment by grenryd** [comment]
Great work Elbowz. Will give it a try as soon as I can.

**Comment by ruuk** [comment]
Waiting for 0.8.16b release, already had 0.8.14b :)

**Comment by elbowz** [comment]
I'm always the last man to know this things!! ;)

@ruuk: master say 0.8.12b (https://github.com/elbowz/xbmc.service.pushbullet/blob/master/addon.xml#L4)
what have you pushed on kody repository (develop branch?)

**Comment by ruuk** [comment]
I've been only pushing develop to my repository.
When we have stable versions, we merge develop into master, and push master into Kodi repository.
So master is always the last stable version, develop is basically testing/unstable.

**Comment by elbowz** [comment]
Ok understand:
- your repo: develop
- kody repo: master

Cool! I can publish this info on main thread, If anyone would like become a beta tester ;)

@grenryd: as ruuk say, you have to wait 0.8.16b (or you can download right now this: https://github.com/elbowz/xbmc.service.pushbullet/archive/develop.zip)

**Comment by ruuk** [comment]
Um... I don't think you merged into develop yet.

**Comment by elbowz** [comment]
I have made a push request...I'll waiting you

Do you want I change the version and changelog?

but how can I know if you have push develop on repo or not ? for the next merge I mean

**Comment by ruuk** [comment]
I'll post a update on the forum like I did with 0.8.14b. Perhaps I will make the posts more clear as to what sort of release it is.

You can change the version/changelog or I will. It'll be an hour or two before I can do the update.

**Comment by elbowz** [comment]
I have added something about it on main topic...but my english as is as. 
If you want add/edit/correct, feel free!

I hope the final users will not be disoriented with a changelog referred to beta and not to stable...

**Comment by ruuk** [comment]
The only thing I would change is Latest release to Latest stable release perhaps?

Also, your changelog and version change were fine, but I had to fix a small bug in the wild import removal 29465a11e8df96d2cd8bb0d9046dfc7e27ea9cd8 - no big deal :)

**Comment by elbowz** [comment]
Thanks for your review!
