### ISSUE TITLE
no attribute 'encode'

### ISSUE THREAD

**Issue by schumi2004** [elbowz/xbmc.service.pushbullet#2]
When I installed addon and configured token it returned below error. Am I missing a module maybe? 

11:28:22 T:1690730816   ERROR: Exception
11:28:22 T:1690730816   ERROR: AttributeError
11:28:22 T:1690730816   ERROR: :
11:28:22 T:1690730816   ERROR: "Pushbullet instance has no attribute '_ws'"
11:28:22 T:1690730816   ERROR:  in
11:28:22 T:1690730816   ERROR: <bound method Pushbullet.__del__ of <lib.pushbullet.Pushbullet instance at 0x5fad78c8>>
11:28:22 T:1690730816   ERROR:  ignored
11:28:22 T:1690730816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'int' object has no attribute 'encode'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/xbmc.service.pushbullet/service.py", line 259, in <module>
                                                Service()
                                              File "/storage/emulated/0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/xbmc.service.pushbullet/service.py", line 47, in **init**
                                                self.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/xbmc.service.pushbullet/service.py", line 98, in run
                                                showNotification(localise(30101), ex.args[0], self.serviceNotifcationTime)
                                              File "/storage/emulated/0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/xbmc.service.pushbullet/lib/common.py", line 28, in showNotification
                                                title.encode('utf-8', 'ignore'), message.encode('utf-8', 'ignore'), timeout, icon))
                                            AttributeError: 'int' object has no attribute 'encode'
                                            -->End of Python script error report<--

**Comment by elbowz** [comment]
Shit! ;)

You are always too speedy ;P

You have an exception when service run, and I have forgotten a type cast..ehmm, sorry

I have just commit a new version: 
- re-download
- uninstall
- try to remove userdata/addon_data/service.pushbullet/settings.xml
- re-install
- enable kodi debug
- re-config setting
- and post xbmc.log on pastebin ;) 

What Kodi version do you have? I'm testing on XBMC 13.2 (Linux machine)

**Comment by schumi2004** [comment]
Have several systems running OpenELEC 4.0.7 (13.2) and some android devices. 1 of them is Helix.

Did a clean install on a windows machine running 13.2
http://pastebin.com/zDea3c4B

Latest commit used https://github.com/elbowz/xbmc.service.pushbullet/commit/51d53738738ef875ad46e6fb3577e37cecce6835

**Comment by elbowz** [comment]
ok, no more 'encode' issue for what I see...It's just a progress ;)

ehm...Can be strange, but close and restart xbmc ;)

**Comment by schumi2004** [comment]
Restarted XBMC, still the same error

http://pastebin.com/Wv7xY7tG

**Comment by elbowz** [comment]
Post the whole log...I have to see If you have service restarting

**Comment by schumi2004** [comment]
Here it is http://xbmclogs.com/show.php?id=305154

edit:
I'll try it in OpenELEC now

**Comment by elbowz** [comment]
sorry schumi2004 for this tedious work...

I had do another commit: b08f25aa385f5c02617cd1c4c037be041cf59321

Try this one...and post log

**Comment by schumi2004** [comment]
Before that commit it returned the same error code 5 in OpenELEC
Then I did a clean install with fake token which returned 30, updated token and installed latest commit, now it's broken.

http://pastebin.com/JpWURMWS

In windows 8
http://pastebin.com/tRL69MDw

**Comment by elbowz** [comment]
remember to enable xbmc debug mode...

**Comment by elbowz** [comment]
I don't understand what kind of error is '5'...

If you have time, try latest: aa8d7c0657ea7328c3c197a86c0858e021e73c09

I hope to have more details on exception

**Comment by schumi2004** [comment]
I installed latest commit and error 5 returned, error 5 is Access denied
I also can't edit Device Info so I edited settings.xml and restarted Kodi, still access denied (error 5)
I grabbed the token from my account settings at pushbullet.com

**Comment by elbowz** [comment]
mmhhh...wait

HTTP Status Code Meanings
200 OK - Everything worked as expected.
400 Bad Request - Usually this results from missing a required parameter.
401 Unauthorized - No valid access token provided.
403 Forbidden - The access token is not valid for that request.
404 Not Found - The requested item doesn't exist.
5XX Server Error - Something went wrong on Pushbullet's side.

I think your error code come from httplib2, but I would get something more human readable.

Device info is disabled, my add-on create a new device on first start, with "xbmc device name"...you have only insert access token.

In the setting: device iden, name and model are set by addon

**Comment by elbowz** [comment]
In your pushbullet device list, do you have a new device created by my add-on?

edit:
in linux you can try:
`curl -u access_token: https://api.pushbullet.com/v2/users/me`
or
`curl -u acces_token: https://api.pushbullet.com/v2/devices`

In windows you can use something like this: http://curl.haxx.se/dlwiz/?type=bin&os=Win64

**Comment by schumi2004** [comment]
No new device created

**Comment by elbowz** [comment]
another thing that can you try is see in _addon/service.pushbullet/.cache_ if there is a file, and open it

**Comment by schumi2004** [comment]
curl commands from cli work, no cache folder found,

**Comment by elbowz** [comment]
Please post your latest xbmc.log with debug activate, and your _userdata/addon_data/service.pushbullet/settings.xml_ (hide your acceess token)

edit: use this latest commit: 22ab4b0e56a4fc4ca2aecc5c40ad91320c6d4cec

**Comment by schumi2004** [comment]
Did a clean install since this is a test PC. Installed PB addon, configured token and left the rest default. And received a new entry in PB devices.
I deleted for example device from PB page since I had 2 of them (from ruuk's addon) and wanted to start clean. Then it brakes, error 5 (and now it's 13)
Reinstalled XBMC and installed addon again and it works, at least no errors.

Installed Youtube and started item, xbmc crashed so i needed to restart, PB broken again.

Can't you change to Oauth like ruuk did?

/edit
Resetting access token didn't help either.

**Comment by elbowz** [comment]
> Installed Youtube and started item, xbmc crashed so i needed to restart, PB broken again.

this is strange!

I don't know how ruuk's Oauth works...In my addon you only have to add the access_token.

If addon don't finds a client iden (pb_client_iden in settings.xml) it creates a new one and set/save the client iden. It's simple, isn't it? :)

I think, if I understand, is the old installation of ruuk addon to do issue...and also this is quite strange...

At the end, you don't have to unistall, reinstall, clean, etc... if you want "reset" my addon (create a new PB client) you have to erase `pb_client_iden` in settings.xml (userdata/addon_data/service.pushbullet/) and at the next xbmc start a new device will be created. 

you can rename the device on pusbullet web page, you'll see reflection on addon settings, at the next xbmc start.

You could see xbmc.log with debug mode enabled, you'll see what happen :)

if do you have a time, could you test my add-on on your different kind of hardware and xbmc version? Thanks!

**Comment by elbowz** [comment]
~~In the next release I'll add a check for test device existence on PB...and all should works good~~

Now I see, It's already in...

**Comment by schumi2004** [comment]
For my understanding, were is the .cache folder located?
It isn't in addons/service.pushbullet.

My mobile complains about read only (error 30) when booting.
Couldn't find .cache folder on other systems either and saw cache errors there also.

**Comment by elbowz** [comment]
yeah, should be in addons/service.pushbullet.

It's managed by httplib2, and created when needed (if web server support cache).

if there is not the folder don't care. 

instead post this "read only" and "cache" errors

**Comment by schumi2004** [comment]
Cache error windows 8
http://pastebin.com/tjQSCBWi

Read only Android mobile
http://pastebin.com/yF8tqisU

Imo there is something wrong with .cache folder

**Comment by elbowz** [comment]
You are obviously a smarty user...

try to change:
`self._h = httplib2.Http(".cache")`  => `self._h = httplib2.Http()`
row 39 of lib/pushbullet.py

I hope httplib2 don't use cache, with this init

**Comment by elbowz** [comment]
if not we should set addonprofile path as .cache...and hope it's writable

In my machine, addon/service.pushbullet is writable ....

**Comment by schumi2004** [comment]
Changing line 39 didn't help. Need to think how i could solve this. Python isn't my best thing

self._h = httplib2.Http(".cache") => self._h = httplib2.Http()
                                                      ^ is under > in line 39 =>
                                            SyntaxError: invalid syntax

**Comment by elbowz** [comment]
ehehe... you are not a smarty user ;P

Indentation error...or you have to substitute whole string: 
`/self._h = httplib2.Http(".cache")/self._h = httplib2.Http()/`

btw, try latest commit: 53f44daab656d6465b620f14657d4b40ede4f71f

**Comment by schumi2004** [comment]
I agree that i'm not a Python expert but i can handle it.
It wasn't a ident error anyway.

So far your latest commit works, device is registered and doing some tests now.

**Comment by elbowz** [comment]
I joke ;)

Thanks for your patience! But do remote debugging is quite hard :)

...and you have all kind of platforms supported by xbmc :+1: 

I'm glad that it's works now...keep me updated

**Comment by elbowz** [comment]
I close this issue...it's become too long. Feel free to open a new one for next trouble
