### ISSUE TITLE
Pushed sent to all devices automatically dismissed by plugin: Version 081b

### ISSUE THREAD

**Issue by jacrify** [elbowz/xbmc.service.pushbullet#22]
To reproduce: Configure plugin to "show notification" for note pushes. Send a note push to all devices from chrome. Push appears on phone, tablet, etc, then appears on kodi. Once kodi processes and displays it, the push is dismissed by kodi, and so disappears from all devices.

If you turn off "show notification", the push stays on the other devices as designed. Same if I turn off XBMC. 

I've run with debug turned on, but in both the failure and sucess cases the log just shows two lines:

23:30:25 T:140488669636352   DEBUG: [Pushbullet]: Updating last_modified: 1417869017.86
23:30:25 T:140488669636352   DEBUG: [Pushbullet]: New push (note) received: blah blah json blah

Love your  addon guys :)

**Comment by jacrify** [comment]
Version 081b

**Comment by elbowz** [comment]
Yeah...I have deleted my answer after see your issue title :)

I'll investigate

**Comment by jacrify** [comment]
Thanks. I wasn't going to mentioned that it was in the title :)

**Comment by elbowz** [comment]
I don't think nothing change but you can test the latest beta version: http://forum.kodi.tv/showthread.php?tid=204567&pid=1837322#pid1837322 (Version 0.8.18b)

**Comment by jacrify** [comment]
Sorry, my bad:

I'm on 0.8.18b already. I typed it wrong twice.

**Comment by elbowz** [comment]
I have rapidly see the code...and I hope don't say rubbish.

You have right :) 

This is the behavior of plugin when pushes arrive (not for mirroring pushes that stay undismissed!).

But I don't know it this is a bug...on kodi you are not able to dismiss the pushes.

And if you send a pushes only to kodi? that pushes is never dismissed?

**Comment by ruuk** [comment]
I think we need to make it optional.

**Comment by elbowz** [comment]
@ruuk from your gui can be dismissed a push? I don't remember...in this case can be right what you suggest

p.s. our plugin have more options of kodi ;)

**Comment by ruuk** [comment]
The GUI has the option to delete a push. I should add the option to dismiss a push as well.

**Comment by elbowz** [comment]
With this option could be 1:1 with the official pushbullet client :)

After that, do optional the dismission on pushes arrived is very simple...

ot: @ruuk have you done the alfa repository?

**Comment by ruuk** [comment]
> ot: @ruuk have you done the alfa repository?

Not yet. I've been busy. I was doing some paid Kodi/Python work. I'm almost done with that so I'll be doing some more stuff here soon :)

**Comment by elbowz** [comment]
I'll wait you come back ruuk... :)

In the meantime, I'll try do not too much damage ;)

@jacrify some days and I'll add this options in settings...thank for your issue report

**Comment by jacrify** [comment]
It only happens if you send a push to all. If you send just to kodi the
push just appears on Kodi.

This happens with link pushes too, which is a bit more subtle. If you push
a link to all that is NOT a video  (eg the url of this issue) kodi
dismisses it from all devices also. Ideally if kodi can't show the link it
won't dismiss the push.

I think this behaviour should be off by default if possible. It means if
anyone is using pushbullet as a generic notification system for events  (as
opposed to user generated pushes) , and thus pushing to all devices rather
than something specific, then having kodi in the list of devices causes all
thoses pushes to disappear immediately.

Thanks for looking.

**Comment by elbowz** [comment]
ok...I'll add this options. don't worry.

Only one thing, If you want use Kodi as a generic notification system, you could try to use ephemeral  pushes (mirroring). They are born for it :)

Ciao!

**Comment by elbowz** [comment]
Added in e349649e3d1d12e03437642ddf5e5c8e596115af

you can try it with a manual installation: https://github.com/elbowz/xbmc.service.pushbullet/archive/develop.zip

...or wait that ruuk publish on alfa/beta repository :)

@ruuk: when do you think the time is come for release on official/master the new features?

**Comment by ruuk** [comment]
Anytime should be good. Things seem pretty stable. In fact, even though something is wrong with my Ouya network setup lately (it is always showing "No Network Connection" and I have to unplug and re-plug the network cable to get it to work again - I haven't tried to figure out the issue yet) the addon reconnects fine every time :)
