### ISSUE TITLE
trouble with russian characters (thins thouble with non english characters)

### ISSUE THREAD

**Issue by mr-anton** [elbowz/xbmc.service.pushbullet#23]
In notification in xbmc russian symbols replaced to space or something like this

**Comment by elbowz** [comment]
Thanks for your report...

It's a my mistake on character set...of course

Give me a couple of day...and I'll fix it :)

**Comment by elbowz** [comment]
fixed in 5ec7039cf20d4495650ca68722a8b7572ed51bc7

If you would like try now, download and install (manually) this: https://github.com/elbowz/xbmc.service.pushbullet/archive/develop.zip

Otherwise, wait the release on develop or official channel

Ciao!
