### ISSUE TITLE
"View Channels" not working

### ISSUE THREAD

**Issue by Zvezke** [elbowz/xbmc.service.pushbullet#24]
In spite of having "View Channels" enabled in the addon's settings my subscribed channels (RSS feeds) aren't forwarded to Kodi.

**Comment by elbowz** [comment]
Fixed in 0e5deb14550906f7b8522b6951b3e4bcc2d54e08

If you would like try now, download and install (manually) this: https://github.com/elbowz/xbmc.service.pushbullet/archive/develop.zip

Otherwise, wait the release on develop or official channel

Ciao!
