### ISSUE TITLE
Hebrew default language

### ISSUE THREAD

**Issue by billymcintosh** [elbowz/xbmc.service.pushbullet#28]
On v10.0.0 & Kodi 17 nightlies, the default charset is Hebrew. 

Can't quite find the GUI settings to change to a Latin based language.

**Comment by billymcintosh** [comment]
Sorry, version is 11.0.0.

**Comment by ruuk** [comment]
This doesn't sound like it has anything to do with the Pushbullet addon. I'm not sure what the v11.0.0 refers to, but it's not a version the addon has ever had. If this is actually an issue with the addon, please feel free to re-open the issue with some more details.

**Comment by billymcintosh** [comment]
I took the version directly from the Kodi changelog.   Hebrew was apparently added in 10.0.0 by Guy Almog from Team The Vibe. 

Full text may be garbled though.  It is 

```
10.0.0
- Added hebrew support by Guy Almog From TeamTheVibe0.8.22
- Official repository release
```

The following entry is for 0.8.22b. 

The issue remains though,  everything except the changelog is in Hebrew.

**Comment by ruuk** [comment]
The latest version on the official repo is 0.8.22 the latest version on my repo is 0.8.26b2. You have a version that is a modified version of the official, and has nothing to do with us.
