### ISSUE TITLE
EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by elbowz** [elbowz/xbmc.service.pushbullet#29]
More info on [stackoverflow.com](http://stackoverflow.com/questions/41063914/pushbullet-and-eof-occurred-in-violation-of-protocol-ssl-c590)

Another pushbullet lib with the same [issue](https://github.com/randomchars/pushbullet.py/issues/103)

**Comment by Jodanzuki** [comment]
I have the same issue. Your stackoverflow suggests it is fixed, yet I couldn't make it work.

**Comment by elbowz** [comment]
See on Kodi form

**Comment by Joerchi** [comment]
Same here. Here is my screenshot from my projector after fresh reboot of Raspberry Pi 3 with OSMC: http://abload.de/img/20170101_17342670szm.jpg

8 'eof occurred in violation of protocol

Please fix this. I have also checked out the latest beta from Github Pushbullet 0.8.8b and Python 3.4. No change. Still this error.

**Comment by Joerchi** [comment]
What do you mean with "see on Kodi form"?

**Comment by ruuk** [comment]
He means the Kodi forum thread.

**Comment by elbowz** [comment]
Sorry, my typo...Ruuk have right

**Comment by permster** [comment]
Are you sure this is resolved in the dev branch?  I just downloaded a zip of dev on Windows Kodi 16.1 and I'm getting the same error.  My script.module.requests addon is version 2.9.1.

22:48:23` T:10460   ERROR: C:\Users\travis\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning

22:48:23 T:10460   ERROR: C:\Users\travis\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning

22:48:24 T:11480   DEBUG: ------ Window Init (Pointer.xml) ------

22:48:24 T:10460   ERROR: Traceback (most recent call last):
                                              File "C:\Users\travis\AppData\Roaming\Kodi\addons\service.pushbullet\main.py", line 218, in <module>
                                                handleArg(args[0])
                                              File "C:\Users\travis\AppData\Roaming\Kodi\addons\service.pushbullet\main.py", line 181, in handleArg
                                                linkDevice()
                                              File "C:\Users\travis\AppData\Roaming\Kodi\addons\service.pushbullet\main.py", line 98, in linkDevice
                                                for d in client.getDevicesList():
                                              File "C:\Users\travis\AppData\Roaming\Kodi\addons\service.pushbullet\lib\pbclient.py", line 124, in getDevicesList
                                                req = requests.get(self.baseURL.format('devices'),auth=(self.token,''))
                                              File "C:\Users\travis\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 67, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "C:\Users\travis\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 53, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "C:\Users\travis\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 468, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "C:\Users\travis\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 576, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Users\travis\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 447, in send
                                                raise SSLError(e, request=request)
                                            SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol`

**Comment by elbowz** [comment]
mhhh...on Kodi forum seems that the issue was solve with this release.
but if you continue to have issue...it's not a good news.

are you sure you have latest v0.8.32 plugin version installed?

**Comment by permster** [comment]
Yeah it says 0.8.32 in the add-on information screen.  I just uninstalled it and did an install from zip using the dev branch zip file download.  Same error as I posted in my previous reply.  Do I need to do anything special to install the dev branch version?

**Comment by elbowz** [comment]
Please read the official kodi forum thread (latest posts)...someone have explain how to do

**Comment by permster** [comment]
No there's still some sort of issue going on here.  Others have reported the issue on the forum as well even with the latest dev branch version.  I just tried following the exact steps in the forum posts and I get the same error.  http://forum.kodi.tv/showthread.php?tid=204567&pid=2502689#pid2502689

**Comment by elbowz** [comment]
Sorry, I don't know how to fix your issue on your environment.

Feel free to make a pull request
