### ISSUE TITLE
Playback issues

### ISSUE THREAD

**Issue by schumi2004** [elbowz/xbmc.service.pushbullet#3]
Since registration is working now i tested some example files.

When starting a local ISO no notification was send

16:23:28 T:2724   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: cannot identify image file
                                            Traceback (most recent call last):
                                              File "C:\Users\XBMC\AppData\Roaming\XBMC\addons\xbmc.service.pushbullet-master\lib\common.py", line 119, in onNotification
                                                self.onNotificationAction(sender, method, json)
                                              File "C:\Users\XBMC\AppData\Roaming\XBMC\addons\xbmc.service.pushbullet-master\service.py", line 230, in _onKodiNotification
                                                icon = fileTobase64(posterFile, imgFormat='JPEG', imgSize=(80, 80))
                                              File "C:\Users\XBMC\AppData\Roaming\XBMC\addons\xbmc.service.pushbullet-master\lib\common.py", line 90, in fileTobase64
                                                img = Image.open(file)
                                              File "C:\Program Files (x86)\XBMC\addons\script.module.pil\lib\PIL\Image.py", line 1980, in open
                                                raise IOError("cannot identify image file")
                                            IOError: cannot identify image file
                                            -->End of Python script error report<--

A simple mp4 file did.

**Comment by elbowz** [comment]
All xbmc.log with debug on, please !

EDIT:
for ISO: add-on trigger on `Player.OnPlay` and type: ['movie','song']
what are iso...can you see on log :)

for mp4: seems that PIL (python library for images) don't know the thumbnail image format of your file. It's quite strange (http://effbot.org/imagingbook/formats.htm).

another commit (I have just do it) could fix the second error, but it send only a xbmc default icon.

you have to post whole log next time!

**Comment by schumi2004** [comment]
I can post full debug but when i see this in log 
   raise IOError("cannot identify image file")
I would say my snipped would be sufficient.

But will post full debug log next time, back to testing.

**Comment by elbowz** [comment]
You have right...but for the ISO problem, the addon log can help me.

I don't understand if it works now?!

**Comment by schumi2004** [comment]
Tested it on different system with a demo iso file and it seems to function there although i don't receive PushBullet messages on my other devices from Kodi (i think a Pushbullet site issues) i see it sending a message out

http://pastebin.com/rVnY1uC7
String seems to be empty but it isn't on other media

**Comment by elbowz** [comment]
mhh.. you have closed the issue...do you think it's can be tagged as "solved"?

Sorry, but my english, as you see, is not very well...

> although i don't receive PushBullet messages on my other devices from Kodi (i think a Pushbullet site issues)

You talk about Chrome and Android? 

note: you have well understand how my add-on work, and how read the debug message. Great!

p.s. I have do another little commit, for send filename with your ISO demo
p.s.s. for do some debug, you can use this page: http://jsfiddle.net/pushbullet/u92DA/ and set your access_token. You could see the mirroring pushes to and form your devices

**Comment by schumi2004** [comment]
The addon is configured to send to other devices and how i read this is that it sends to ALL devices connected to my account.
Normally when i receive a message on my mobile it sends out a PB message to AL my other devices, this isn't happening anymore. Also when i send a PB message from website to a specific device and change that device to send the same message to other one from list i receive a error from PB that something went wrong. My best guess is that PB service is having some issues. So i can't really test if Kodi addon is actually sending something. the log file says it does but maybe the service is down/ or having troubles at pushbullet.com?

Did you see my request on forum for a test button in addon settings? So the addon can send a test message out?

**Comment by elbowz** [comment]
mhh...try to disable/shutdown xbmc, and retry again. My addon dismiss message when arrive, but only for the pushes sended directly to Kodi not for mirroring.

But you can try and see if the problem is my addon or pushbullet.com service. You can also see the link http://jsfiddle.net/pushbullet/u92DA/ for see what appen.

...I have answer your question on forum.

**Comment by schumi2004** [comment]
The iso test file i have was giving errors after your latest commit http://pastebin.com/BPZPHSzz

Finally got it working that PushBullet addon sends messages. But I didn't received them on my mobile but on laptop only. Strange that it doesn't get pushed to all PB registered devices.

**Comment by elbowz** [comment]
sorry guy, my stupid mistake...

I'm adding your requested testing button in settings...give me a bit of time for fix the bug.

> Finally got it working that PushBullet addon sends messages

Finally? Do you have change something, or was it a pushbullet.com issue?

**Comment by schumi2004** [comment]
With finally i mean that i can see them on my laptop were i have Chrome installed with PushBullet extension installed.

And here comes the strange thing. I'm not sure how PB works.
The first time I installed it it was to send notifications on my phone to laptop/desktop.
The only time i seen notifications on my phone was when i manually send a message from pushbullet website.

So this is how i tested.
XBMC installed with Pushbullet addon on Laptop and Mobile
PushBullet app installed on my mobile. (Android)
Chrome installed with Pushbullet extension on Laptop

Send test message from Pushbullet website to all 4 instances separately, this works. I see test message send from website in xbmc on my phone, in xbmc on my laptop, in pushbullet app on my mobile and chrome notification.

So I have 4 devices that can receive pushbullet notifications!
I started to play media in XBMC on Laptop but only received pushbullet message from chrome extension, NOT in XBMC on Mobile and NOT in Pushbullet App on Mobile.

So i played media in XBMC on Mobile and again only received message from chrome extension and not on other instances.

Strange right?

**Comment by schumi2004** [comment]
I think there should be an option to configure receiving device in addon settings so you can force push notifications to selected device.

Currently it's sending to all PB instances right in PB addon?

**Comment by elbowz** [comment]
You are the best tester I have ever meet ;) :+1: 

With your help I think my add-on will grow up quite speedy.

I have just commit a new release, try it now (there is a "send a test notification" button that you have requested :)

**Comment by elbowz** [comment]
> I think there should be an option to configure receiving device in addon settings so you can force push notifications to selected device.

Works like android pushbullet client (there you can't select WHO have to receive the notification)...indeed the protocol not support selective/restricted receiver (I spoke about mirroring/sync mode)

**Comment by elbowz** [comment]
For this reason I have added the filters!
Client always receive the pushes, but can restrict which view...

In your case the problem is on Android/Chrome client...My add-on can do it!!! :)

**Comment by schumi2004** [comment]
Tried the test button functionality but it seems to do nothing, in fact i'm not seeing any notifications at all now, not even in Chrome. But if I look at the changes you filtered Chrome.

edit\
Log shows it did send something
16:12:07 T:556   DEBUG: [Pushbullet]: Ephemeral push sended: Left Behind (2014) - Some were saved, and some were...

Strange thing is why I don't see any message/notification from PB in Android App or other XBMC client

**Comment by schumi2004** [comment]
In PB Android App you can't do anything with filtering from external sources like in this case XBMC addon. You can only prevent/filter apps on your phone to send notifications to desktop.

**Comment by schumi2004** [comment]
PushBullet addon launched from Programs in XBMC

http://pastebin.com/8sRa38zC

**Comment by elbowz** [comment]
> In PB Android App you can't do anything with filtering from external sources like in this case XBMC addon. You can only prevent/filter apps on your phone to send notifications to desktop.

Yeah, I what I try to say you, my add-on stay ahead the pushbullet android app ;P
or translated, for how the pushbullet protocol is thought: You have to ask this new features to pushbullet.com. I can't do nothing in my app to "select" receiver of mirror/sync in outbound

**Comment by schumi2004** [comment]
Are you sure you can't push to device?
According API docs it should be possible https://docs.pushbullet.com/v2/pushes/

Push to a device

POST https://api.pushbullet.com/v2/pushes
Target Parameters

Each push has a target, if you don't specify a target, we will broadcast it to all of the current account's devices. Only one target may be specified.

device_iden - Send the push to a specific device. Appears as target_device_iden on the push.
email - Send the push to this email address. If that email address is associated with a Pushbullet user, we will send it directly to that user, otherwise we will fallback to sending an email to the email address (this will also happen if a user exists but has no devices registered).

**Comment by elbowz** [comment]
> PushBullet addon launched from Programs in XBMC

Fixed in the latest released

**Comment by elbowz** [comment]
> Are you sure you can't push to device?

Yes, I'm sure :) 

How you can read, the pushes can you send to: https://docs.pushbullet.com/v2/pushes/ are only:

```
type=note
title - The note's title.
body - The note's message.
type=link
title - The link's title.
body - A message associated with the link.
url - The url to open.
type=address
name - The place's name.
address - The place's address or a map search query.
type=list
title - The list's title.
items - The list items, a list of strings e.g. ["one", "two", "three"].
type=file
file_name - The name of the file.
file_type - The MIME type of the file.
file_url - The url where the file can be downloaded.
body - A message to go with the file.
```

For mirroring/sync you have to use type = "mirror"...there are the "secret" API that Pushbullet support team explain me (thanks chris), and this API are not public

**Comment by elbowz** [comment]
but the strange is that "send a test notification" don't works.

On my Chrome/Android/Kodi works like a charm ! Shit!

**Comment by schumi2004** [comment]
How i read the API docs is that you can send to specific device using device_iden, mirroring isn't really needed since most users (i think) would like to receive messages on specific device only?
I could be wrong about this though.

If it's not possible to send to other device then the API docs is misleading,

I can contact Pushbullet devs to ask for support on this but i think they would direct me back to the https://docs.pushbullet.com/v2/pushes/ API stuff.

**Comment by elbowz** [comment]
You don't trust me! :P

You can send to specific device using device_iden only: notes, links, list, address and file NOT mirror

mirror It's quite different, I can set icon and it's used for keep synced notification on all device.

I can also send a note when Kodi playback something, but It's wrong (imho) (for icon, dismission, and other stuffs)

EDIT:
for understand: mirror pushes is used when you enable (in pushbullet android app): "Beta: Sync my notification with my other Android device too ...."

**Comment by schumi2004** [comment]
I do trust you but maybe I don't understand mirror function. Mirror for me means send/synchronise to all devices?

**Comment by elbowz** [comment]
> Mirror for me means send/synchronise to all devices?

exactly! **ALL** devices :)

EDIT:
You can try this function if you have two or more Android devices (or my addon)

You can ask to pushbullet guys...

**Comment by elbowz** [comment]
**more important stuff:**

What works and what not works?
...and where it works (Android, Chrome, Helix, etc..)

**Comment by schumi2004** [comment]
Currently push/send only works for Chrome addon (atleast for me)  when you remove it's filter. And desktop client. All other clients don't receive anything

**Comment by schumi2004** [comment]
For me pushing to a single client would be enough

**Comment by elbowz** [comment]
Chrome addon != desktop client ?!?

> when you remove it's filter  

what filter?

> All other clients don't receive anything  

have you enable the setting: "Beta: Sync my notification with my other Android device too ...."

"Send a test notification" works?

**Comment by elbowz** [comment]
> For me pushing to a single client would be enough

I can't send a "notification" but only a note

**Comment by schumi2004** [comment]
Desktop client and Chrome extension are different things yes, see Pushbullet website. Enabling beta doesn't make sense if android client doesn't receive anything in the first place. Sending a note would be perfect since you will recieve a sort of notification on your mobile which you can use to trigger Tasker

**Comment by elbowz** [comment]
You have right, sorry...On linux there isn't desktop client :(

> Enabling beta doesn't make sense if android client doesn't receive anything in the first place.  

I would try...

> Sending a note would be perfect since you will recieve a sort of notification on your mobile which you can use to trigger Tasker

I can add it on the future release, but I have to find a way to add it also in add-on settings.
although If the problem is only tasker, I think should be better do a feature request to pushbullet team.
Mirror push exist for a reason...Note push exist for another one...

**Comment by schumi2004** [comment]
Can't we loopin @Pushbullet devs in this thread? 
I'll try to request it but for now push is only usable for chrome addon or desktop client.

**Comment by schumi2004** [comment]
@elbowz changing type to note here isn't enough right? https://github.com/elbowz/xbmc.service.pushbullet/blob/master/lib/pushbullet.py#L256

**Comment by elbowz** [comment]
grrrr! ...no :)

That you have linked are **Ephemeral** pushes...it's different.

But I repeat: It's not a problem send a note:

> I can add it on the future release, but I have to find a way to add it also in add-on settings.
> although If the problem is only tasker, I think should be better do a feature request to pushbullet team.
> **Mirror push exist for a reason...Note push exist for another one...***

You can do me a suggestion for settings, and I can evalutate your suggestion :) 
But what you want (imho) it's wrong...

Works or not works on Android? If not it's quite unusefull

**Comment by elbowz** [comment]
@schumi2004 what do you think to use _Tasker/Event/UI/Notifcation_ trigger as **workaround** for your problem, in the meantime?

It's works good...but you have to match something in the notification title...that I use for:
- filename
- movie title
- song title

**Comment by schumi2004** [comment]
That's the best solution yes. You always have to use a match word or something like that. With IFTTT I used some string in url. For PB notes you could let the user specify the key word or multiple words with content data added to it by XBMC PB addon

**Comment by schumi2004** [comment]
If you don't do any matching your task won't know what to do with different notes, links etc. It will then trigger action on every note recieved. If you want to perform before and after actions 2 notes should be (optional) send. If you want to dim and turn on lights for example

**Comment by elbowz** [comment]
mhhh...I think I'm not explained.

My addon will not send notes, but always the ephemeral push (mirroring)...but I see you can catch that with Tasker (Android)...after that you can do what you want (IFTTT stuff, etc...)

**Comment by elbowz** [comment]
es. 

Kodi playback something => My add-on push mirroring => Tasker (android) trigger notification (not pb push) => do your stuff

**Comment by schumi2004** [comment]
I know your addon doesn't send notes but it was for explaining. I only think if you want to use such messages you do need to send notes or url or something else other then ephemeral since the Pb app can't handle those atm

**Comment by schumi2004** [comment]
But if you don't want to implement such then it's fine. Then ill need to find another way. When I saw this addon I immediately thought this is perfect until I found out the previous issues mentioned

**Comment by elbowz** [comment]
Sorry, I don't understand... Pushbullet app handle my mirroring (ephemeral) push they are in them standard.

I follow the Pushbullet directive (protocol)...

And you can trigger Pushbullet app notification with Tasker, How I have explained above

**Comment by elbowz** [comment]
If I use notes as you want, after 10 played songs, your android notification area will be full!!

...and you can't have notification on iphone, android, windows, chrome. This is the reason because ephemeral pushes exist.

but for you what is the difference? tasker can trigger also ephemeral pushes by android notification (I have tested it)

**Comment by schumi2004** [comment]
I meant the Pushbullet apps available for phones, the ephemeral messages never reach those. They only show up in PB apps for desktop or chrome extension. Mentioned it before.
You told me to address this to PB dev team, I did that recently.

Tasker is also a mobile (android) application. Using notes or other options (ephemeral messages never show up) 
![2014_10_02_21 14 52](https://cloud.githubusercontent.com/assets/968545/4496728/b13c0b5a-4a68-11e4-8cd3-e31cd32113c4.png)

So when you receive a note (that is the best item to put much data in it) on playback you can trigger silence phone and dim light for example.

New note on finished playback (or stop)  set ringer volume and lights back for example.
Both need to have a different keyword.

Pushbullet plugin for tasker can trash note, close or do nothing with it.

That's a use case example for me.

**Comment by elbowz** [comment]
an image speaks a thousand words

**Comment by schumi2004** [comment]
Maybe i should have posted them sooner, sorry  ;)

**Comment by elbowz** [comment]
an image speaks a thousand words
![image](https://cloud.githubusercontent.com/assets/1451484/4496932/ac215bd2-4a6a-11e4-854f-8561886563c7.png)
(I can't upload image from my android)

**Comment by elbowz** [comment]
how you can see...the first android notification is Yatse...

...the second is my add-on and your hated ephemeral push ;)

I think you don't trust me :p 

Ephemeral push is born for Android!

**Comment by schumi2004** [comment]
Don't get me wrong, I don't hate them. They just don't appear on my device and I wonder if you can use them in Tasker?

**Comment by elbowz** [comment]
> > Enabling beta doesn't make sense if android client doesn't receive anything in the first place.
> > I would try...

Do you have try after?

**Comment by schumi2004** [comment]
Enabled it this morning, will try again. Btw test button didn't work here.

**Comment by elbowz** [comment]
Work like a charm with tasker (workaround): I HAVE JUST TESTED THEM!!!

I have wrote it above!

**Comment by elbowz** [comment]
If they appear on Chrome/Windows and you have enabled (Beta) option on Android: must works

**Comment by schumi2004** [comment]
You are right about enabling beta, my apologies.
Now i need to figure out how to separate XBMC messages from others to use for tasks but that's a different issue.

I did noticed some errors in openelec and for now it doesn't seem to work in OpenELEC
http://xbmclogs.com/show.php?id=309102

line 1716
line 2536
line 3308

And maybe something is still wrong with *.iso files, didn't recieved notices from it on Windows, rest worked perfect.

**Comment by elbowz** [comment]
Sorry @schumi2004 , but If you open an issue and don't listen me and don't follow my suggestions, it's quite hard help you...I'm gentle but also busy and with this behavior you waste my time.

Sorry guy, but I'm quite frustrated when someone ask me support and continue to ask without listen and try. So it's only useful for lose your and my time.
