### ISSUE TITLE
Action on pushes dismissed (Android)

### ISSUE THREAD

**Issue by elbowz** [elbowz/xbmc.service.pushbullet#6]
"Action on pushes dismissed" works on Chrome but it does not on Android...I have wrote to Pushbullet team (I hope answer me).

**Comment by elbowz** [comment]
@christopherhesse for reproduce the issue:
1. Ephemeral push is send by my client (Kodi add-on)
   `{"type":"push","targets":["stream","android"],"push":{"body":"body","notification_id":73122259,"source_device_iden":"xxxxx","package_name":"com.xbmc.service.pushbullet","title":"title","has_root":true,"notification_tag":null,"source_user_iden":"xxx","application_name":"Pushbullet Kodi Add-on","client_version":126,"dismissable":true,"type":"mirror","icon":"[...]"}}`
2. Notification is appear correctly on Chorme and on Android device

3.A I dismiss notification on Chrome => Dismissed pushed correctly send
`{"type":"push","targets":["stream","android"],"push":{"type":"dismissal","package_name":"com.xbmc.service.pushbullet","notification_id":-289522402,"notification_tag":null,"source_user_iden":"xxx"}}`

3.B I dismiss (swipe notification) on Android device => NOTHING HAPPEN!

Could the issue be depend from the device definition that send the ephemeral message (kodi add-on)?:
`{"active":true,"iden":"xxxx","created":1.411897924479964e+09,"modified":1.413625164928313e+09,"type":"stream","kind":"stream","nickname":"MeanMachine","manufacturer":"Linux","model":"Kodi","pushable":true}`

**Comment by elbowz** [comment]
I have found the problem...but It's quite strange...

Seems changing the **package_name** solve the issue!!

ruuk, do you have an android device? can you test this bug? I think that could be a problem only of my client.

**Comment by ruuk** [comment]
I'll try it when i get home.
By the way, I don't know if you noticed, but the created and modified items have values like 1.411897924479964e+09 which doesn't seem right.

**Comment by elbowz** [comment]
why not?

if you do `curl -u <access toekn>: -X GET https://api.pushbullet.com/v2/devices`

what do you get?

**Comment by ruuk** [comment]
Well modified and created should be unixtime. Is that outgoing or incoming message.

Can't do the curl at the moment. I'm on my phone at work.

**Comment by ruuk** [comment]
Well modified and created should unixtime
I get the same with the curl command though.

**Comment by elbowz** [comment]
mhhh...

1.411897924479964e+09 = 1411897924.479964 = Sun, 28 Sep 2014 09:52:04 GMT

Why Do you say it's wrong?

**Comment by ruuk** [comment]
I guess nothing :) The notation threw me off, as I've never seen it with a unixtime. Silly me.

**Comment by elbowz** [comment]
don't worry :yum: 

If you can try to reproduce this strange bug...I'm quite sure I have added `"package_name":"com.xbmc.service.pushbullet"` in some kind of blacklist on my android pb client...but I don't know I did that?!?

**Comment by ruuk** [comment]
I was able to play a video on XBMC, get a notification on my Android device. I swiped away the notification and the video stopped.

**Comment by elbowz** [comment]
cool...and thanks!

this means that my android pb client is messed up...

Main rule of Computer Science:
1. check the power plug is connected
2. try to reboot
3. re-install 

the third can be my solution... ;P
