### ISSUE TITLE
Push media don't playback

### ISSUE THREAD

**Issue by elbowz** [elbowz/xbmc.service.pushbullet#8]
Hi ruuk, 

 I know the issue form is for end users...but I'm also an end user of Pushbullet add-on :)

Maybe, when add-on receive a push link with a "raw" media (kodi supported) playback don't start.

For reproduce the issue can you try to push this link: http://movietrailers.apple.com/movies/independent/beforeigotosleep/beforeigotosleep-tlrr_h480p.mov

**Comment by ruuk** [comment]
I think the issue form is good for developers as well. It's a good tool to let us communicate.

My first thought was that I needed to set the user agent. That didn't work. I'll look at it some more.

**Comment by elbowz** [comment]
Can you reproduce the bug?

I don't think is the user agent, my add-on did a playlist through the xbmc json

**Comment by ruuk** [comment]
I reproduced it. It is weird because the url is passed to XBMC, but XBMC fails on playback. That's why I thought it might be a user agent issue. Setting a user agent didn't help though. I'll figure it out :)

**Comment by elbowz** [comment]
I'm sure of that! ...if you can help you, try to see my old code. I did a simple call to executeJsonRPC (now, I'm on smartphone...I can not be more deep and detailed)

**Comment by elbowz** [comment]
mhhh... now, I'm without my pc.

I have seen a rapidly your code, I think I'm wrong, but the issue (also for latest issue on posted on xbmc forum) is here: https://github.com/elbowz/xbmc.service.pushbullet/blob/master/lib/pushhandler.py#L118 

on **playMedia**. 

I think you have to clear playlist before do a new one...but tomorrow I can do some test. 

I also think that if we use youtube plugin the tags (title, thumbs, etc...) are already filled.

tomorrow I'll be able to say you more :)

**Comment by ruuk** [comment]
> I think you have to clear playlist before do a new one...

You're right. I should have looked at your json code in the first place :) Fixed and it works correctly now. I will post an update soon.

> I also think that if we use youtube plugin the tags (title, thumbs, etc...) are already filled.

True. That is why I had to use xbmc.Player().Play(), so I could add the data to the ListItem. We can't use the youtube plugin because it is usually broken and besides, it doesn't handle the 270 other sites that youtube-dl module handles. This method will also in the future allow us to set the tags for direct video links or set it with data from the push itself.

**Comment by elbowz** [comment]
good!

I'll test your fix...this also fix this issue?

**Comment by elbowz** [comment]
Seems the issue is fixed, don't works only on movietrailers.apple.com, but apple is apple (read closed (read shit))

if you try: https://archive.org/download/HouseOfFrankenstein-Trailer/Trailer-HouseOfFrankenstein.divx

works like a charm

**Comment by ruuk** [comment]
Nope. Still working on it. I tried using your original json code, but got the same result. There is something about the url that Kodi doesn't like. I'm going to look at how youtube-dl handles that video and see if that tells me something.

**Comment by elbowz** [comment]
How you prefer...for me the trouble is Apple :)

**Comment by ruuk** [comment]
It was a user agent issue. If I set the user agent to:

`QuickTime compatible (Kodi)`

It works. I will just set the User-Agent to this for .mov files (or perhaps only .mov files on apple.com)
